name: Test

on:
  push:
  pull_request:

jobs:
  test-leiningen:
    name: Test Leiningen

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # Disabled because of 100s of Caused by: java.lang.ClassNotFoundException: com.apple.eawt.QuitHandler
          # https://discourse.processing.org/t/error-hello-processing-jdk-10-osx-high-sierra-com-apple-eawt-quithandler-not-supported/1396 may be relevant.
          # - macOS-latest
          # Disabled because it's hanging somewhere in lein test (or at least not finishing after 6m+)
          # possibly related to missing imagemagick on windows?
          # - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          lein: 2.10.0

      - name: Cache Leiningen dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: lein-${{ runner.os }}-${{ hashFiles('**/project.clj') }}
          restore-keys: lein-${{ runner.os }}-

      - name: Leiningen Install
        run: lein install

      - name: Version
        run: lein version

      - name: Leiningen Test
        uses: coactions/setup-xvfb@v1
        with:
          run: lein test

      - name: Upload Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: snippet-differences-${{ github.sha }}.${{ github.run_attempt }}
          path: |
            dev-resources/snippet-snapshots/*/*/*-actual.png
            dev-resources/snippet-snapshots/*/*/*-difference.png

  test-cljs:
    name: Test ClojureScript

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache deps.edn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: cljs-${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: cljs-${{ runner.os }}-

      # Java 17 generates class file version 61.0, which is what processing has
      # been compiled with.
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: latest
          bb: latest

      - name: System Info
        run: bb system-info

      - name: Install Processing jars
        run: bb processing-install

      # AOT compile applet-listener and applet so CLJS compile can run
      - name: AOT Compile
        run: clojure -T:build aot

      - name: Test
        uses: coactions/setup-xvfb@v1
        with:
          run: clojure -Mfig:cljs-test

  test-clj:
    name: Test Clojure

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          # Failing because setup-xvfb powershell can't find clojure commands
          # - windows-latest
        java-version: [17] # ,20 to test jdk20

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache deps.edn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: clj-${{ runner.os }}-jdk${{ matrix.java-version }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: clj-${{ runner.os }}-jdk${{ matrix.java-version }}-

      # Java 17 generates class file version 61.0, which is what processing has
      # been compiled with.
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: latest
          bb: latest

      - name: System Info
        run: bb system-info

      - name: Install Processing jars
        run: bb processing-install

      # AOT compile applet-listener and applet
      - name: AOT Compile
        run: clojure -T:build aot

      - name: Test
        uses: coactions/setup-xvfb@v1
        with:
          run: clojure -X:test
