name: Test

on:
  push:

jobs:
  test-cljs:
    name: Test ClojureScript

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache deps.edn dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.cpcache
            ~/.gitlibs
          key: cljs-${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: cljs-${{ runner.os }}-

      # Java 17 generates class file version 61.0, which is what processing has
      # been compiled with.
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: latest
          bb: latest

      - name: System Info
        run: bb system-info

      # AOT compile applet-listener and applet so CLJS compile can run
      - name: AOT Compile
        run: clojure -T:build aot

      - name: Test
        uses: coactions/setup-xvfb@v1
        with:
          run: clojure -Mfig:cljs-test

  test-clj:
    name: Test Clojure

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # SEGV on CGLDescribeRenderer after WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)
          # - macOS-latest
          # Failing because setup-xvfb powershell can't find clojure commands
          # - windows-latest
        java-version: [17] # ,20 to test jdk20

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache deps.edn dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.cpcache
            ~/.gitlibs
          key: clj-${{ runner.os }}-jdk${{ matrix.java-version }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: clj-${{ runner.os }}-jdk${{ matrix.java-version }}-

      # Java 17 generates class file version 61.0, which is what processing has
      # been compiled with.
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: latest
          bb: latest

      - name: System Info
        run: bb system-info

      # AOT compile applet-listener and applet
      - name: AOT Compile
        run: clojure -T:build aot

      # Ie all the tests excluding snippet tests, many of which are also
      # verified from a CLJS context.
      - name: Test
        uses: coactions/setup-xvfb@v1
        with:
          run: clojure -X:test :excludes "[:clj-snippets :cljs-snippets]"

      - name: Test CLJ Snippet Snapshots
        uses: coactions/setup-xvfb@v1
        with:
          run: clojure -X:test :includes "[:clj-snippets]"

      # FIXME: Disabled for now, need to standup a webserver before executing
      # - name: Test CLJS Snippet Snapshots
      #   uses: coactions/setup-xvfb@v1
      #   with:
      #     run: clojure -X:test :includes '[:cljs-snippets]'

      - name: Upload Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: snippet-differences-${{ github.sha }}.${{ github.run_attempt }}
          path: |
            dev-resources/snippet-snapshots/*/*/*-actual.png
            dev-resources/snippet-snapshots/*/*/*-difference.png
